const AUTHENTICATE_USER = "AUTHENTICATE_USER"; 
const UPDATE_CART = "UPDATE_CART";
const UPDATE_PROMO = "UPDATE_PROMO";
const SWITCH_THEME = "SWITCH_THEME";

export { AUTHENTICATE_USER, UPDATE_CART, UPDATE_PROMO,SWITCH_THEME};
